Enable creating guest memory regions with create_guest_memfd() and set_user_memory_region2()
containers/libkrun pull request #211
Opened 2024-07-29 15:46 UTC by MatiasVara

This is a WIP commit.

2025-01-09 21:33 UTC, jakecorrenti commented
@MatiasVara is this ready for review, or should I wait?

2025-01-09 21:40 UTC, tylerfanelli commented
@jakecorrenti I'm addressing the KVM guest_memfd changes (which @MatiasVara also added in this PR) to my latest SEV-SNP patches. This will probably require a rebase after that. After that, it will likely be ready for a review.

2025-01-10 09:34 UTC, MatiasVara commented
> @jakecorrenti I'm addressing the KVM guest_memfd changes (which @MatiasVara also added in this PR) to my latest SEV-SNP patches. This will probably require a rebase after that. Once that happens, it will likely be ready for a review.

I think the PR is ready to review. The current issue is that it does not work for the latest series for KVM (v6). I am investigating the issue.

2025-02-12 10:59 UTC, MatiasVara commented
I just updated the PR with the fix for v6 series. The fix is only to set the `KVM_ARM_VCPU_REC` feature during the initialization of VCPUs otherwise `vcpu_finalize` would fail.

2025-02-12 11:39 UTC, MatiasVara commented
@jakecorrenti @tylerfanelli @slp Feel free to give a quick look. I am pretty sure there many things to fix.

2025-02-24 21:25 UTC, jakecorrenti requested changes
I didn't actually run it, just looked at the code. Overall looks good. Few comments, though.

Thanks for the work!

2025-02-24 21:25 UTC, jakecorrenti commented on src/vmm/src/builder.rs
> +use crossbeam_channel::Sender;
We already import this for macos

2025-02-24 21:25 UTC, jakecorrenti commented on src/vmm/src/builder.rs
> +use kvm_bindings::KVM_ARM_VCPU_REC;
```suggestion
#[cfg(feature = "cca")]
use kvm_bindings::KVM_ARM_VCPU_REC;
```

2025-02-24 21:25 UTC, jakecorrenti commented on src/vmm/src/builder.rs
>          #[cfg(feature = "net")]
Should this be CCA only? There's another one a few lines below as well

2025-02-24 21:25 UTC, jakecorrenti commented on src/vmm/src/linux/vstate.rs
> +};
Arm-specific bindings shouldn't be imported for all flavors

2025-02-24 21:25 UTC, jakecorrenti commented on src/vmm/src/linux/vstate.rs
> +                Unsupported(39) => Ok(VcpuEmulation::Handled),
leftover TODO

2025-02-24 21:25 UTC, jakecorrenti commented on src/vmm/src/linux/vstate.rs
> +        sender_io: Sender<MemProperties>,
should be CCA only

2025-02-24 21:25 UTC, jakecorrenti commented on src/vmm/src/builder.rs
> +    sender_io: Sender<MemProperties>,
should be CCA only

2025-02-25 15:17 UTC, MatiasVara commented on src/vmm/src/builder.rs
>          #[cfg(feature = "net")]
I can't remember why I commented this line.

2025-02-25 18:49 UTC, MatiasVara commented on src/vmm/src/linux/vstate.rs
> +};
Should I import them only when `#[cfg(feature = "tee")]`?

2025-02-25 20:13 UTC, jakecorrenti commented on src/arch/Cargo.toml
> +kvm-ioctls = { version = ">=0.17", git = "https://github.com/virtee/kvm-ioctls", branch = "cca" }
Exactly. I'm going to have to make some changes for my TDX work, so I think we'll need to merge your CCA work and my TDX work into the main branch and then use that here.

2025-02-26 03:21 UTC, tylerfanelli commented on src/vmm/src/linux/vstate.rs
> +        sender_io: Sender<MemProperties>,
The memory fault exception isn't TEE-specific (although it could be used that way), so I don't think I agree that this should be CCA only.

2025-02-26 03:28 UTC, jakecorrenti commented on src/vmm/src/linux/vstate.rs
> +        sender_io: Sender<MemProperties>,
You're right. I did this part of the review before you and I had talked about the order of patches.

2025-02-26 10:57 UTC, MatiasVara commented on src/libkrun/src/lib.rs
>          ctx_cfg.shutdown_efd,
I am not sure about the design either.  I do not like that all flavors spawn an extra thread so I think I will change that. Why couldn't you have a function signature as you proposed?

2025-02-26 16:31 UTC, MatiasVara commented on src/libkrun/src/lib.rs
> +                            let host_startaddr = m.addr + offset;
Yes, it is based on `ram_block_discard_range()`. You are right, it should use actual host address. Thanks.

2025-02-26 16:32 UTC, MatiasVara commented on src/libkrun/src/lib.rs
> +                                let _ret = madvise(
Right. How do I handle the error in this case?

2025-02-27 15:10 UTC, MatiasVara commented on src/devices/Cargo.toml
> +cca = []
Should I not leave `tee =[]` here?

2025-02-27 15:20 UTC, jakecorrenti commented on src/devices/Cargo.toml
> +cca = []
You should. I think that was a suggestion error. I was trying to suggest just getting rid of `default = ...`

2025-02-27 15:22 UTC, jakecorrenti commented on src/libkrun/src/lib.rs
> +                                let _ret = madvise(
I don't know how to handle this off the top of my head, but at the very least I think we should probably check if the ret value is < 0 and then log the error

2025-02-27 15:27 UTC, MatiasVara commented on src/libkrun/src/lib.rs
> +                                let _ret = madvise(
Yes, I will check for that condition.

2025-03-04 10:35 UTC, MatiasVara commented on src/arch/Cargo.toml
> +cca = []
If I understand correctly, when I compile with cca flags:
```bash
cargo build --release --features cca
```
The `tee` feature would be enabled. However, most of the code for `tee` is not required and I ended up doing this everywhere:
```diff
-    #[cfg(feature = "tee")]
+    #[cfg(all(feature = "tee", not(feature = "cca")))]
     let qboot_bundle = vm_resources
         .qboot_bundle()
         .ok_or(StartMicrovmError::MissingKernelConfig)?;
```
Can't be `cca` just a different feature?

2025-03-13 13:32 UTC, MatiasVara commented on src/vmm/src/linux/vstate.rs
> +                Unsupported(39) => Ok(VcpuEmulation::Handled),
After checking this, I figured out this should remain. I'll explain in the code.

2025-03-13 14:47 UTC, MatiasVara commented on src/libkrun/src/lib.rs
> +
The problem here is that I still need the index to get the fd.

2025-03-13 15:23 UTC, MatiasVara commented on src/libkrun/src/lib.rs
> +
I open https://github.com/rust-vmm/vm-memory/issues/315 because I think we need an structure to keep track of the mapping `guestdf_mem` and `regions`.

2025-03-17 11:30 UTC, MatiasVara commented on src/vmm/src/linux/vstate.rs
> +        sender_io: Sender<MemProperties>,
I think we can enable the extra this extra thread only when the `tee` feature is enabled.

2025-03-17 13:14 UTC, MatiasVara commented
After reviewing the Jake comments I came to the conclusion that this PR should be split otherwise is hard to review:

0. Add `Use create_guest_memfd() and set_user_memory_region2()` only when `tee` is enabled.
1. Add the handling of `KVM_MEMORY_FAULT` only for `tee`, which includes the extra thread for handling shared to private and viceverse.
2. `Tee` should be replaced with `tee and x86-64` since all `tee` is for `x86-64`.
3. Add CCA support. This shall be added with `cca and tee` enabled.

2025-03-17 21:28 UTC, jakecorrenti commented on src/libkrun/src/lib.rs
> +
Great idea. I'll keep track of that

2025-03-17 21:33 UTC, jakecorrenti commented
> After reviewing the Jake comments I came to the conclusion that this PR should be split otherwise is hard to review:
> 
>     0. Add `Use create_guest_memfd() and set_user_memory_region2()` only when `tee` is enabled.
> 
>     1. Add the handling of `KVM_MEMORY_FAULT` only for `tee`, which includes the extra thread for handling shared to private and viceverse.
> 
>     2. `Tee` should be replaced with `tee and x86-64` since all `tee` is for `x86-64`.

I don't know if this is idiomatic by any means, but could we have something like `tee-x86` and `tee`? `tee-x86` for the x86 specific functionality, and then `tee` for the shared bits? Would that be cleaner than just writing `#[cfg(all(feature = "tee", target_arch = "x86"))]`? Again, I don't know if that's "proper" Rust. 
> 
>     3. Add CCA support. This shall be added with `cca and tee` enabled.
> 
>     4. Eventually some code will be shared for `tee` in `x86-64` and `aarch64` but I can't see it yet.
> 
> 
> @jakecorrenti @tylerfanelli @slp WDYT?

Other than my question above, that all sounds good to me.

2025-03-18 00:22 UTC, tylerfanelli commented
> After reviewing the Jake comments I came to the conclusion that this PR should be split otherwise is hard to review:
> 
> 0. Add `Use create_guest_memfd() and set_user_memory_region2()` only when `tee` is enabled.

I don't think `set_user_memory_region2` should be `tee` only, as I believe that on newer kernels, `set_user_memory_region` is deprecated.

> 1. Add the handling of `KVM_MEMORY_FAULT` only for `tee`, which includes the extra thread for handling shared to private and viceverse.

I'm addressing that in my SEV-SNP PR currently.

> 2. `Tee` should be replaced with `tee and x86-64` since all `tee` is for `x86-64`.

Makes sense to me.

> 3. Add CCA support. This shall be added with `cca and tee` enabled.

Do you mean `aarch64 and tee`?

2025-03-18 10:15 UTC, MatiasVara commented
> > After reviewing the Jake comments I came to the conclusion that this PR should be split otherwise is hard to review:
> > ```
> > 0. Add `Use create_guest_memfd() and set_user_memory_region2()` only when `tee` is enabled.
> > 
> > 1. Add the handling of `KVM_MEMORY_FAULT` only for `tee`, which includes the extra thread for handling shared to private and viceverse.
> > 
> > 2. `Tee` should be replaced with `tee and x86-64` since all `tee` is for `x86-64`.
> > ```
> 
> I don't know if this is idiomatic by any means, and it depends on whether you can have target arch-specific features, but could we have something like `tee-x86` and `tee`? `tee-x86` for the x86 specific functionality, and then `tee` for the shared bits? Would that be cleaner than just writing `#[cfg(all(feature = "tee", target_arch = "x86_64"))]`? Again, I don't know if that's "proper" Rust or even possible.
> 
I do not know either. I though that `tee and x86` would have code that `tdx` and `snv` share, if that exists.

> > ```
> > 3. Add CCA support. This shall be added with `cca and tee` enabled.
> > 
> > 4. Eventually some code will be shared for `tee` in `x86-64` and `aarch64` but I can't see it yet.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @jakecorrenti @tylerfanelli @slp WDYT?
> 
> Other than my question above, that all sounds good to me.

2025-03-18 10:31 UTC, MatiasVara commented
> > After reviewing the Jake comments I came to the conclusion that this PR should be split otherwise is hard to review:
> > 
> > 0. Add `Use create_guest_memfd() and set_user_memory_region2()` only when `tee` is enabled.
> 
> I don't think `set_user_memory_region2` should be `tee` only, as I believe that on newer kernels, `set_user_memory_region` is deprecated.
> 

That's OK. I could just leave `set_user_memory_region2` for the future.

> > 1. Add the handling of `KVM_MEMORY_FAULT` only for `tee`, which includes the extra thread for handling shared to private and viceverse.
> 
> I'm addressing that in my SEV-SNP PR currently.
> 

OK but I need to split those chunks from my PR anyway.

> > 2. `Tee` should be replaced with `tee and x86-64` since all `tee` is for `x86-64`.
> 
> Makes sense to me.
> 
> > 3. Add CCA support. This shall be added with `cca and tee` enabled.
> 
> Do you mean `aarch64 and tee`?

Yes for the moment.

2025-03-19 17:02 UTC, MatiasVara commented
> After reviewing the Jake comments I came to the conclusion that this PR should be split otherwise is hard to review:
> 
> 0. Add `Use create_guest_memfd() and set_user_memory_region2()` only when `tee` is enabled.
> 1. Add the handling of `KVM_MEMORY_FAULT` only for `tee`, which includes the extra thread for handling shared to private and viceverse.
> 2. `Tee` should be replaced with `tee and x86-64` since all `tee` is for `x86-64`.
> 3. Add CCA support. This shall be added with `cca and tee` enabled.
> 4. Eventually some code will be shared for `tee` in `x86-64` and `aarch64` but I can't see it yet.
> 
> @jakecorrenti @tylerfanelli @slp WDYT?

I just split the PR into a few commits. It is the same code though. The first three commits are independent of cca and should be shared by all tees.

2025-05-14 09:47 UTC, MatiasVara commented
I've Just rebased the PR and tried it on v8 series.

2025-07-24 15:04 UTC, MatiasVara commented
I just rebased and tested on v8. Also, I am now relying on the rust-vmm/kvm repo.

2025-07-24 15:06 UTC, MatiasVara commented
I think the following issues shall be addressed before merging:
- [x] support for blk
- [x] Check the EXIT_FAULT
- [ ] Check FDT hardcoded
- [x] Try v9 series

2026-06-04 18:16 UTC, jakecorrenti commented
I'm going to close this for the time being since there hasn't been any activity in 11 months. Feel free to re-open it whenever you want to start working on it again.

2026-06-04 18:16 UTC, closed without merging