net: Allow creating vsocks in listen mode.
containers/libkrun pull request #246
Opened 2024-12-31 20:08 UTC by WhatAmISupposedToPutHere

Previously all vsocks were expected to be connected from the guest. This patch adds support for sockets that are listened to by the guest and are connected from the host.

2025-01-06 21:34 UTC, tylerfanelli reviewed
Any readily-available testing methods?

2025-01-06 21:39 UTC, WhatAmISupposedToPutHere commented
Build the linked PR from muvm, and launch a second command in the same vm. The second one will use this feature to send the launch request.

2025-01-08 15:19 UTC, slp commented on src/libkrun/src/lib.rs
>      let filepath = match CStr::from_ptr(c_filepath).to_str() {
When `listen == true`, please also check if the path exists, failing if that's the case. It'd be also nice checking if the dirname is okay.

This allows us to return an early error to the library user, as otherwise can be a bit confusing.

2025-01-08 15:20 UTC, slp requested changes
This looks great, thanks. I only requested a minor change to force the library users to provide a healthy path for the unix socket.

2025-01-08 16:43 UTC, mtjhrc commented on src/libkrun/src/lib.rs
>      let filepath = match CStr::from_ptr(c_filepath).to_str() {
I think `krun_add_vsock_port2` with `listen = true` could just `bind` the socket before returning. This would more robustly verify the path is in fact a socket and not something else and just save the socket `fd` in the `unix_ipc_port_map`.

2025-01-08 17:02 UTC, mtjhrc commented
Thanks, I'll try to test this later, but for now I realized something:

If I am not mistaken, this only starts listening on the socket once the vsock device is activated, so if you want to connect to the socket from host, you would have to wait until the guest boot process initializes the vsock device. 
Is this intended or useful for your use case? If so It should at least be documented, because the users of libkrun could easily run into a race condition where they sometimes try to connect to the socket before the guest boots. An alternative could be to also call `listen` on the socket before `krun_add_vsock_port2` returns.

2025-01-08 17:25 UTC, WhatAmISupposedToPutHere commented
Yes, the socket file appearing only after the vm is ready to process incoming connection is desired, that way the vm can wait for the file to appear before sending the requests.

2025-01-13 14:37 UTC, slp commented
@mtjhrc Do you want to take a second look or can we merge it already?

2025-01-13 15:00 UTC, mtjhrc approved these changes
Sorry for the delay. I managed to test this just by adding a listening vsock in `chroot_vm` and using it in the guest. 
Now I understand how it's meant to be used. Still I am unsure if we generally want to bind the sockets at the device initialization stage, but if It works for you this is fine for now, and we could always add another API later.

So for me this is good to merge! Thanks

2025-01-14 10:00 UTC, slp approved these changes

2025-01-14 10:00 UTC, merged